package programa;

import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mathe
 */
public class TelaPrincipal extends javax.swing.JFrame {

    String[ ] jogos = new String[20];
    float[ ] precos = new float[20];
    String email,  senha;
    
    private Login login;
    private Cadastro cadastro;
    private Carrinho carrinho;
    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal(){
        initComponents();
        this.login = new Login();
        this.cadastro = new Cadastro();
        this.carrinho = new Carrinho();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        Minecraft4 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        btnCarrinho4 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        Overwatch6 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        GrandTheftAutoV4 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        LeagueOfLegends9 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        NBA2K23 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        Valorant = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        FIFA23 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuUsuario = new javax.swing.JMenu();
        btnLogin = new javax.swing.JMenuItem();
        btnLogout = new javax.swing.JMenuItem();
        menuCartegorias = new javax.swing.JMenu();
        btnAventura = new javax.swing.JMenuItem();
        btnAcao = new javax.swing.JMenuItem();
        btnCorrida = new javax.swing.JMenuItem();
        btnEsporte = new javax.swing.JMenuItem();
        btnLuta = new javax.swing.JMenuItem();
        btnTerror = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(943, 1040));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setAutoscrolls(true);
        jPanel7.setPreferredSize(new java.awt.Dimension(943, 500));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel7MouseEntered(evt);
            }
        });

        Minecraft4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Minecraft/Minecraft_capa.png"))); // NOI18N
        Minecraft4.setText("jLabel1");
        Minecraft4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minecraft4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinecraftMouseClicked(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel41.setText("Destaques");

        jLabel42.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("Minecraft");

        jLabel43.setText("R$ 22,90");

        btnCarrinho4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/3144456.png"))); // NOI18N
        btnCarrinho4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCarrinho4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCarrinhoMouseClicked(evt);
            }
        });

        jLabel44.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel44.setText("Populares");

        jLabel45.setText("Gratuito");

        Overwatch6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Overwatch2/overwatch-2_x1j6.jpg"))); // NOI18N
        Overwatch6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Overwatch6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Overwatch2MouseClicked(evt);
            }
        });

        jLabel46.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("Overwatch 2");

        jLabel47.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("Grand Theft Auto V");

        jLabel48.setText("RS 53,33");

        GrandTheftAutoV4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/GrandTheftAutoV/Grand_Theft_Auto_V_capa.png"))); // NOI18N
        GrandTheftAutoV4.setText("jLabel1");
        GrandTheftAutoV4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GrandTheftAutoV4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GrandTheftAutoVMouseClicked(evt);
            }
        });

        jLabel49.setText("Gratuito");

        LeagueOfLegends9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/LeagueOfLegends/5bfdc36b22e14.jpg"))); // NOI18N
        LeagueOfLegends9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LeagueOfLegends9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LeagueOfLegends1MouseClicked(evt);
            }
        });

        jLabel50.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setText("League of Legends");

        jLabel51.setText("R$ 299,90 ");

        NBA2K23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/NBA2K23/nba-2k23-next-gen-version_ej55.jpg"))); // NOI18N
        NBA2K23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NBA2K23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NBA2K23Overwatch2MouseClicked(evt);
            }
        });

        jLabel52.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel52.setText("NBA 2K23");

        jLabel53.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel53.setText("Valorant");

        jLabel54.setText("Gratuito");

        Valorant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Valorant/5ec161df463ab.jpg"))); // NOI18N
        Valorant.setText("jLabel1");
        Valorant.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Valorant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ValorantGrandTheftAutoVMouseClicked(evt);
            }
        });

        jLabel55.setText("R$ 299,90 ");

        FIFA23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/FIFA23/fifa-23_tw92.jpg"))); // NOI18N
        FIFA23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FIFA23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FIFA23Overwatch2MouseClicked(evt);
            }
        });

        jLabel56.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel56.setText("FIFA 23");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCarrinho4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel44)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel49)
                                            .addComponent(LeagueOfLegends9, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel50))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel42, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Minecraft4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel43))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel48)
                                            .addComponent(GrandTheftAutoV4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(19, 19, 19))
                                    .addComponent(jLabel47, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel54)
                                            .addComponent(Valorant, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(19, 19, 19))
                                    .addComponent(jLabel53, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(Overwatch6))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addComponent(jLabel45))
                                    .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel51)
                                            .addComponent(NBA2K23))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel55)
                                            .addComponent(FIFA23))))))
                        .addGap(0, 348, Short.MAX_VALUE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel41)
                    .addComponent(btnCarrinho4))
                .addGap(15, 15, 15)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Overwatch6)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel46)
                                .addGap(156, 156, 156)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel45))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NBA2K23)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel52)
                                .addGap(156, 156, 156)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel51))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FIFA23)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel56)
                                .addGap(156, 156, 156)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel55)))
                .addGap(20, 20, 20)
                .addComponent(jLabel44)
                .addGap(15, 15, 15)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel50)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LeagueOfLegends9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel49))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addComponent(jLabel42)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Minecraft4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel43))
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addComponent(jLabel47)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(GrandTheftAutoV4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel48)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel53)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Valorant)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel54)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(730, Short.MAX_VALUE)
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(176, 176, 176))
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(394, 394, 394))
        );

        jScrollPane2.setViewportView(jPanel1);

        menuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pacote de Icones/icons 1/user.png"))); // NOI18N
        menuUsuario.setText("Usuário");
        menuUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuUsuario.setPreferredSize(new java.awt.Dimension(72, 22));

        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pacote de Icones/icons 1/user_add.png"))); // NOI18N
        btnLogin.setText("Login");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        menuUsuario.add(btnLogin);

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pacote de Icones/icons 1/door_out.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        menuUsuario.add(btnLogout);

        jMenuBar1.add(menuUsuario);

        menuCartegorias.setText("Categorias");
        menuCartegorias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnAventura.setText("Aventura");
        btnAventura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAventura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAventuraActionPerformed(evt);
            }
        });
        menuCartegorias.add(btnAventura);

        btnAcao.setText("Ação");
        btnAcao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcaoActionPerformed(evt);
            }
        });
        menuCartegorias.add(btnAcao);

        btnCorrida.setText("Corrida");
        btnCorrida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCorrida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorridaActionPerformed(evt);
            }
        });
        menuCartegorias.add(btnCorrida);

        btnEsporte.setText("Esporte");
        btnEsporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEsporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsporteActionPerformed(evt);
            }
        });
        menuCartegorias.add(btnEsporte);

        btnLuta.setText("Luta");
        btnLuta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLutaActionPerformed(evt);
            }
        });
        menuCartegorias.add(btnLuta);

        btnTerror.setText("Terror");
        btnTerror.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTerror.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerrorActionPerformed(evt);
            }
        });
        menuCartegorias.add(btnTerror);

        jMenuBar1.add(menuCartegorias);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    private void btnTerrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerrorActionPerformed
        Terror terror = new Terror();
        terror.setVisible(true);
        terror.setLocationRelativeTo(null);
        terror.setTitle("Jogos de Terror");

        for (int c = 0; c < jogos.length; c++) {
            terror.jogo[c] = jogos[c];
            terror.preco[c] = precos[c];
        }

        terror.email = email;
        terror.senha = senha;
        dispose();
    }//GEN-LAST:event_btnTerrorActionPerformed

    private void btnLutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLutaActionPerformed
        Luta luta = new Luta();
        luta.setVisible(true);
        luta.setLocationRelativeTo(null);
        luta.setTitle("Jogos de Luta");

        for (int c = 0; c < jogos.length; c++) {
            luta.jogo[c] = jogos[c];
            luta.preco[c] = precos[c];
        }

        luta.email = email;
        luta.senha = senha;
        dispose();
    }//GEN-LAST:event_btnLutaActionPerformed

    private void btnEsporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsporteActionPerformed
        Esporte esporte = new Esporte();
        esporte.setVisible(true);
        esporte.setLocationRelativeTo(null);
        esporte.setTitle("Jogos de Esporte");

        for (int c = 0; c < jogos.length; c++) {
            esporte.jogo[c] = jogos[c];
            esporte.preco[c] = precos[c];
        }

        esporte.email = email;
        esporte.senha = senha;
        dispose();
    }//GEN-LAST:event_btnEsporteActionPerformed

    private void btnCorridaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorridaActionPerformed
        Corrida corrida = new Corrida();
        corrida.setVisible(true);
        corrida.setLocationRelativeTo(null);
        corrida.setTitle("Jogos de Corrida");

        for (int c = 0; c < jogos.length; c++) {
            corrida.jogo[c] = jogos[c];
            corrida.preco[c] = precos[c];
        }
        corrida.email = email;
        corrida.senha = senha;
        dispose();
    }//GEN-LAST:event_btnCorridaActionPerformed

    private void btnAcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcaoActionPerformed
        Acao acao = new Acao();
        acao.setVisible(true);
        acao.setLocationRelativeTo(null);
        acao.setTitle("Jogos de Ação");

        for (int c = 0; c < jogos.length; c++) {
            acao.jogo[c] = jogos[c];
            acao.preco[c] = precos[c];
        }
        acao.email= email;
        acao.senha = senha;
        dispose();
    }//GEN-LAST:event_btnAcaoActionPerformed

    private void btnAventuraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAventuraActionPerformed
        Aventura aventura = new Aventura();
        aventura.setVisible(true);
        aventura.setLocationRelativeTo(null);
        aventura.setTitle("Jogos de Aventura");

        for (int c = 0; c < jogos.length; c++) {
            aventura.jogo[c] = jogos[c];
            aventura.preco[c] = precos[c];
        }
        aventura.email = email;
        aventura.senha = senha;
        dispose();
    }//GEN-LAST:event_btnAventuraActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        login.usuarioLogin = null;
        login.senhaLogin = null;
        btnLogin.setVisible(true);
        btnLogout.setVisible(false);
        email = "";
        
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        login.setVisible(true);
        login.setLocationRelativeTo(null);
        login.setTitle("Login");
        dispose();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void LeagueOfLegends1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LeagueOfLegends1MouseClicked
        LeagueOfLegendsGame leagueOfLegendsGame = new LeagueOfLegendsGame();
        leagueOfLegendsGame.setVisible(true);
        leagueOfLegendsGame.setLocationRelativeTo(null);
        leagueOfLegendsGame.setTitle("league of Legends");

        for (int c = 0; c < jogos.length; c++) {
            leagueOfLegendsGame.jogo[c] = jogos[c];
            leagueOfLegendsGame.preco[c] = precos[c];
        }
        leagueOfLegendsGame.email = email;
        leagueOfLegendsGame.senha = senha;
        dispose();
    }//GEN-LAST:event_LeagueOfLegends1MouseClicked

    private void GrandTheftAutoVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrandTheftAutoVMouseClicked
        GrandTheftAutoVGame grandTheftAutoVGame = new GrandTheftAutoVGame();
        grandTheftAutoVGame.setVisible(true);
        grandTheftAutoVGame.setLocationRelativeTo(null);
        grandTheftAutoVGame.setTitle("Grand Theft Auto V");

        for (int c = 0; c < jogos.length; c++) {
            grandTheftAutoVGame.jogo[c] = jogos[c];
            grandTheftAutoVGame.preco[c] = precos[c];
        }
        grandTheftAutoVGame.email = email;
        grandTheftAutoVGame.senha = senha;
        dispose();
    }//GEN-LAST:event_GrandTheftAutoVMouseClicked

    private void Overwatch2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Overwatch2MouseClicked
        Overwatch2Game overwatch2Game = new Overwatch2Game();
        overwatch2Game.setVisible(true);
        overwatch2Game.setLocationRelativeTo(null);
        overwatch2Game.setTitle("Overwatch");

        for (int c = 0; c < jogos.length; c++) {
            overwatch2Game.jogo[c] = jogos[c];
            overwatch2Game.preco[c] = precos[c];
        }
        overwatch2Game.email = email;
        overwatch2Game.senha = senha;
        dispose();
    }//GEN-LAST:event_Overwatch2MouseClicked

    private void btnCarrinhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCarrinhoMouseClicked

        carrinho.setVisible(true);
        carrinho.setTitle("Carrinho");
        carrinho.setLocationRelativeTo(null);

        int condicao = 0, c = 0;

        do {

            if(jogos[c] == null) {
                condicao = 1;
            } else {
                carrinho.nomesDosJogos[c] = jogos[c];
                carrinho.precosDosJogos[c] = precos[c];
            }

            c++;

        } while (condicao != 1 || c < 20 );

        carrinho.email = email;
        carrinho.senha = senha;
        
        dispose();
    }//GEN-LAST:event_btnCarrinhoMouseClicked

    private void MinecraftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinecraftMouseClicked
        MinecraftGame minecraftGame = new MinecraftGame();
        minecraftGame.setVisible(true);
        minecraftGame.setLocationRelativeTo(null);
        minecraftGame.setTitle("Minecraft");

        for (int c = 0; c < jogos.length; c++) {
            minecraftGame.jogo[c] = jogos[c];
            minecraftGame.preco[c] = precos[c];
        }
        minecraftGame.email = email;
        minecraftGame.senha = senha;
        dispose();
    }//GEN-LAST:event_MinecraftMouseClicked

    private void NBA2K23Overwatch2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NBA2K23Overwatch2MouseClicked
        NBA2K23Game nBA2K23Game = new NBA2K23Game();
        nBA2K23Game.setVisible(true);
        nBA2K23Game.setLocationRelativeTo(null);
        nBA2K23Game.setTitle("NBA 2K23");

        for (int c = 0; c < jogos.length; c++) {
            nBA2K23Game.jogo[c] = jogos[c];
            nBA2K23Game.preco[c] = precos[c];
        }
        nBA2K23Game.email = email;
        nBA2K23Game.senha = senha;
        dispose();
    }//GEN-LAST:event_NBA2K23Overwatch2MouseClicked

    private void ValorantGrandTheftAutoVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ValorantGrandTheftAutoVMouseClicked
        ValorantGame valorantGame = new ValorantGame();
        valorantGame.setVisible(true);
        valorantGame.setLocationRelativeTo(null);
        valorantGame.setTitle("Valorant");

        for (int c = 0; c < jogos.length; c++) {
            valorantGame.jogo[c] = jogos[c];
            valorantGame.preco[c] = precos[c];
        }
        valorantGame.email = email;
        valorantGame.senha = senha;
        dispose();
    }//GEN-LAST:event_ValorantGrandTheftAutoVMouseClicked

    private void jPanel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseEntered
        if(email == null) {
            btnLogin.setVisible(true);
            btnLogout.setVisible(false);
        } else {
            btnLogin.setVisible(false);
            btnLogout.setVisible(true);
        }
    }//GEN-LAST:event_jPanel7MouseEntered

    private void FIFA23Overwatch2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FIFA23Overwatch2MouseClicked
        FIFA23Game fIFA23Game = new FIFA23Game();
        fIFA23Game.setVisible(true);
        fIFA23Game.setLocationRelativeTo(null);
        fIFA23Game.setTitle("FIFA 23");

        for (int c = 0; c < jogos.length; c++) {
            fIFA23Game.jogo[c] = jogos[c];
            fIFA23Game.preco[c] = precos[c];
        }
        fIFA23Game.email = email;
        fIFA23Game.senha = senha;
        dispose();
    }//GEN-LAST:event_FIFA23Overwatch2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
     
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaPrincipal telaPrincipal = new TelaPrincipal();
                telaPrincipal.setVisible(true);
                telaPrincipal.setLocationRelativeTo(null);
                telaPrincipal.setTitle("Tela Principal");
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FIFA23;
    private javax.swing.JLabel GrandTheftAutoV4;
    private javax.swing.JLabel LeagueOfLegends9;
    private javax.swing.JLabel Minecraft4;
    private javax.swing.JLabel NBA2K23;
    private javax.swing.JLabel Overwatch6;
    private javax.swing.JLabel Valorant;
    private javax.swing.JMenuItem btnAcao;
    private javax.swing.JMenuItem btnAventura;
    private javax.swing.JLabel btnCarrinho4;
    private javax.swing.JMenuItem btnCorrida;
    private javax.swing.JMenuItem btnEsporte;
    private javax.swing.JMenuItem btnLogin;
    private javax.swing.JMenuItem btnLogout;
    private javax.swing.JMenuItem btnLuta;
    private javax.swing.JMenuItem btnTerror;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenu menuCartegorias;
    private javax.swing.JMenu menuUsuario;
    // End of variables declaration//GEN-END:variables
}
